version: '{build}'
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\Build.ps1
test: off
artifacts:
- path: .\.nuget\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  name: nuget.org
  api_key:
    secure: # add your encrypted apikey here!
  on:
    branch: master
    appveyor_repo_tag: true
